### ISSUE TITLE
Orphaned ALICA Monitor window cannot be closed if ALICA Setup window is closed

### ISSUE THREAD

**Issue by kmdouglass** [MStefko/ALICA#2]
This is only a minor bug.

If you close the ALICA Setup window without first clicking *Stop* and with the ALICA Monitor still open, then you cannot close the ALICA Monitor window without first reopening ALICA Setup and clicking Stop.

One possible way to fix this is always first call the *Stop* button's callback when *Exit* is clicked in the ALICA Setup window.

**Comment by MStefko** [comment]
Do you have the latest ALICA version? I thought I set it up so that at one
time there can be only either Monitor or Setup window opened. It's possible
that it's not yet  in the latest release though.

**Comment by kmdouglass** [comment]
> Do you have the latest ALICA version?

Yes. I tried both building ALICA.jar myself and the .jar file included in the v0.1.2 release and experience the strange behavior in both.

It's possible that there are slight differences in the way the GUI works on Linux/Windows or between the Sun JDK and OpenJDK because I am noticing some strange alignment errors on my laptop. For example, see the leftmost column of labels in the image below:

![gui_alignment](https://user-images.githubusercontent.com/3697676/27202384-b6e618f2-5221-11e7-9946-def12ba2f884.png)

If you can't repeat the behavior in this issue, then it very well may be related to differences in the choice of JDK.

**Comment by MStefko** [comment]
Yeah, that seems like a JDK version issue. Oracle does provide binaries for Linux and Mac, is there any reason to use OpenJDK? Did you try running my .jar release on Linux with the Oracle-provided JRE?

**Comment by kmdouglass** [comment]
OK, I found a very large hint as to what the cause of the problem is: it's the presence of the SASS .jar file in the ImageJ plugins folder. If SASS is present, I can reproduce the issue with both OpenJDK and the Sun JDK, and on both Windows and Linux. However, if I remove SASS_v0.1.2.jar from *MM2ROOT/plugins*, then the problems with the GUI windows disappear entirely.

I don't immediately know why ALICA's GUI would behave differently with and without the SASS plugin. Any ideas @MStefko ?

**Comment by MStefko** [comment]
Okay, that is some funny behavior 😄 .

SASS was never meant to be used within Micro-Manager, it works best as either a standalone .jar or within FIJI (ImageJ 1.50e, running JRE1.6). So I would advise against putting the SASS jar file anywhere into the Micro-Manager classpath.

The reason for this behavior is, that SASS uses ALICA as a source (for the Analyzers and Controllers), and ALICA in turn uses MicroManager libraries. Since I want the SASS.jar to be completely standalone (and not throw any weird NoClassDefFoundErrors), I am using a build script for both SASS and ALICA that copies every necessary class into the .jar (this is also why the file size is so big, because they copy a lot of the ImageJ and MicroManager classes, instead of just expecting that they will be found somewhere in the classpath at runtime). This means that SASS.jar actually contains the (older) ALICA release, which are probably loaded before the updated ALICA which has the window problem fixed.

We can discuss whether this design choice is optimal, but nevertheless, SASS.jar has no business being within the MicroManager classpath. I think that the BeanShell scripting interface is the best for controlling SASS, but using FIJI with a 1.6 JRE is also an option.

**Comment by kmdouglass** [comment]
Thanks for the explanation. I suspected that this might be the problem.

I'll make note of this in the documentation's FAQ in case other people attempt the same thing that I did. I think we can go ahead and close this issue then.
